Improve output on both success/error scenario

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -2,6 +2,20 @@
 
 set -euo pipefail
 
+# Curl that will return non-zero exit code,
+# but still return its' response if it fails.
+# ( https://superuser.com/a/1641410/215321 )
+curlf() {
+  OUTPUT_FILE=$(mktemp)
+  HTTP_CODE=$(curl --silent --output $OUTPUT_FILE --write-out "%{http_code}" "$@")
+  if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
+    >&2 cat $OUTPUT_FILE
+    exit 22
+  fi
+  cat $OUTPUT_FILE
+  rm $OUTPUT_FILE
+}
+
 USERNAME=$(printenv ${BUILDKITE_PLUGIN_GITHUB_STATUS_USERNAME_ENV:-"GITHUB_USERNAME"})
 TOKEN=$(printenv ${BUILDKITE_PLUGIN_GITHUB_STATUS_TOKEN_ENV:-"GITHUB_TOKEN"})
 REPO_ORG=$(basename $(dirname $BUILDKITE_REPO) | sed 's/git@github.com://')
@@ -12,7 +26,7 @@ TARGET_URL=${BUILDKITE_PLUGIN_GITHUB_STATUS_TARGET_URL:-""}
 DESCRIPTION=${BUILDKITE_PLUGIN_GITHUB_STATUS_DESCRIPTION:-""}
 CONTEXT=${BUILDKITE_PLUGIN_GITHUB_STATUS_CONTEXT:-""}
 
-curl \
+curlf \
   -X POST \
   -u $USERNAME:$TOKEN \
   -H "Accept: application/vnd.github.v3+json" \
